/**
 * Box canonical-bytes serializer tests (phase 2f Stop γ Task 6).
 *
 * Each fixture entry provides two expected byte sequences generated by
 * sigma-rust:
 *   `full_hex`   — `ErgoBox::sigma_serialize_bytes()` (full box, with tx_id + index)
 *   `no_ref_hex` — `ErgoBox::bytes_without_ref()` (body only, no tx_id/index)
 *
 * The test reconstructs an `ErgoBox` from the `box_json` field, calls
 * `serializeBoxBytes` and `serializeBoxBytesWithoutRef`, and asserts
 * byte-for-byte equality.
 *
 * Sigma-rust refs:
 *   chain/ergo_box.rs:195-198 (bytes_without_ref)
 *   chain/ergo_box.rs:201-223 (sigma_serialize for ErgoBox)
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { serializeBoxBytes, serializeBoxBytesWithoutRef } from '../../src/wire/ergo-box-bytes'
import { SValueSerializeError } from '../../src/wire/serialize-svalue'
import { parseSType } from '../../src/wire/parse-stype'
import { parseSValue } from '../../src/wire/parse-svalue'
import { ByteReader } from '@ergots/scorex'
import type { ErgoBox, SType } from '../../src/mir/types'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// ---------------------------------------------------------------------------
// Fixture types
// ---------------------------------------------------------------------------

interface TokenJson {
  id_hex: string
  amount: string // decimal string for u64
}

interface RegisterJson {
  id: number // 4..=9
  constant_hex: string // SType + SValue bytes as hex
}

interface BoxJsonFields {
  value: string // decimal string for u64
  ergo_tree_hex: string
  creation_height: number
  tokens: TokenJson[]
  registers: RegisterJson[]
  tx_id_hex: string
  index: number
}

interface BoxBytesEntry {
  name: string
  description: string
  full_hex: string
  no_ref_hex: string
  box_json: BoxJsonFields
}

interface BoxBytesFixture {
  entries: BoxBytesEntry[]
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function hexToBytes(hex: string): Uint8Array {
  const result = new Uint8Array(hex.length / 2)
  for (let i = 0; i < hex.length; i += 2) {
    result[i / 2] = parseInt(hex.slice(i, i + 2), 16)
  }
  return result
}

/**
 * Reconstruct an `ErgoBox` from the `box_json` fields in the fixture.
 *
 * Register reconstruction parses the `constant_hex` bytes (Constant =
 * SType + SValue bytes) using the same parsers the production code uses.
 */
function reconstructErgoBox(bj: BoxJsonFields): ErgoBox {
  const value = BigInt(bj.value)
  const ergoTreeBytes = hexToBytes(bj.ergo_tree_hex)
  const creationHeight = bj.creation_height
  const txId = hexToBytes(bj.tx_id_hex)
  const index = bj.index

  const tokens = bj.tokens.map((t) => ({
    id: hexToBytes(t.id_hex),
    amount: BigInt(t.amount),
  }))

  const registers: Record<number, { tpe: SType; value: ReturnType<typeof parseSValue> } | undefined> = {}
  for (const reg of bj.registers) {
    const constBytes = hexToBytes(reg.constant_hex)
    const reader = new ByteReader(constBytes)
    const tpe = parseSType(reader)
    const regValue = parseSValue(tpe, 0, reader)
    registers[reg.id] = { tpe, value: regValue }
  }

  return { value, ergoTreeBytes, creationHeight, tokens, registers, txId, index }
}

// ---------------------------------------------------------------------------
// Load fixture
// ---------------------------------------------------------------------------

const fixturePath = join(__dirname, '../fixtures/wire/ergo-box-bytes.json')
const fixture: BoxBytesFixture = JSON.parse(readFileSync(fixturePath, 'utf8'))

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('serializeBoxBytes (full: with tx_id + index)', () => {
  for (const entry of fixture.entries) {
    it(`matches sigma-rust for ${entry.name}: ${entry.description}`, () => {
      const box = reconstructErgoBox(entry.box_json)
      const expected = hexToBytes(entry.full_hex)
      const actual = serializeBoxBytes(box)
      expect(actual).toEqual(expected)
    })
  }
})

describe('serializeBoxBytesWithoutRef (no tx_id + index)', () => {
  for (const entry of fixture.entries) {
    it(`matches sigma-rust for ${entry.name}: ${entry.description}`, () => {
      const box = reconstructErgoBox(entry.box_json)
      const expected = hexToBytes(entry.no_ref_hex)
      const actual = serializeBoxBytesWithoutRef(box)
      expect(actual).toEqual(expected)
    })
  }
})

describe('serializeBoxBytes error guards', () => {
  /** Minimal valid box for error tests. */
  function makeBox(overrides: Partial<ErgoBox> = {}): ErgoBox {
    return {
      value: 1_000_000n,
      ergoTreeBytes: new Uint8Array([0x08, 0x00]),
      registers: {},
      tokens: [],
      creationHeight: 0,
      txId: new Uint8Array(32),
      index: 0,
      ...overrides,
    }
  }

  /** Assert a `SValueSerializeError` with the expected error code. */
  function expectCode(fn: () => unknown, code: string): void {
    expect(fn).toThrow(SValueSerializeError)
    try {
      fn()
    } catch (e) {
      expect(e).toBeInstanceOf(SValueSerializeError)
      expect((e as SValueSerializeError).code).toBe(code)
    }
  }

  /** N tokens with 32-byte ids and small amounts. */
  function makeTokens(n: number): { id: Uint8Array; amount: bigint }[] {
    return Array.from({ length: n }, (_, i) => ({
      id: new Uint8Array(32).fill(i & 0xff),
      amount: BigInt((i % 100) + 1),
    }))
  }

  // F5 batch 5: the egress bound is the u8 wire ceiling (255) — JVM
  // putUByte(size) asserts 0..255 (ErgoBoxCandidate.scala:144; scorex-util
  // putUByte). The old >122 threshold mirrored sigma-rust's BoundedVec count
  // cap; the JVM applies NO size window on egress either — the 4096-byte
  // window is a parse-only rule (see sbox-token-window.test.ts).
  it('serializes 123 tokens (old count cap removed)', () => {
    const box = makeBox({ tokens: makeTokens(123) })
    expect(() => serializeBoxBytes(box)).not.toThrow()
    expect(() => serializeBoxBytesWithoutRef(box)).not.toThrow()
  })

  it('serializes 255 tokens (at the u8 wire ceiling; no egress size window)', () => {
    const box = makeBox({ tokens: makeTokens(255) })
    expect(() => serializeBoxBytes(box)).not.toThrow()
    expect(() => serializeBoxBytesWithoutRef(box)).not.toThrow()
  })

  it("rejects tokens.length > 255 with 'sbox-tokens-out-of-range'", () => {
    const box = makeBox({ tokens: makeTokens(256) })
    expectCode(() => serializeBoxBytes(box), 'sbox-tokens-out-of-range')
    expectCode(() => serializeBoxBytesWithoutRef(box), 'sbox-tokens-out-of-range')
  })

  it("rejects token id length != 32 with 'token-id-length'", () => {
    const box = makeBox({
      tokens: [{ id: new Uint8Array(16), amount: 1n }],
    })
    expectCode(() => serializeBoxBytes(box), 'token-id-length')
    expectCode(() => serializeBoxBytesWithoutRef(box), 'token-id-length')
  })

  it("rejects gapped registers with 'sbox-registers-not-dense'", () => {
    const box = makeBox({
      registers: {
        5: { tpe: { tag: 'SLong' }, value: { kind: 'Long', value: 0n } },
      },
    })
    expectCode(() => serializeBoxBytes(box), 'sbox-registers-not-dense')
    expectCode(() => serializeBoxBytesWithoutRef(box), 'sbox-registers-not-dense')
  })

  it("rejects txId length != 32 with 'txid-length' (full only)", () => {
    const box = makeBox({ txId: new Uint8Array(16) })
    expectCode(() => serializeBoxBytes(box), 'txid-length')
    // serializeBoxBytesWithoutRef does NOT write txId — no error expected there
    expect(() => serializeBoxBytesWithoutRef(box)).not.toThrow()
  })

  it("rejects index > 65535 with 'sbox-index-out-of-range' (full only)", () => {
    const box = makeBox({ index: 70_000 })
    expectCode(() => serializeBoxBytes(box), 'sbox-index-out-of-range')
    // serializeBoxBytesWithoutRef does NOT write index — no error expected there
    expect(() => serializeBoxBytesWithoutRef(box)).not.toThrow()
  })

  it("rejects negative index with 'sbox-index-out-of-range' (full only)", () => {
    const box = makeBox({ index: -1 })
    expectCode(() => serializeBoxBytes(box), 'sbox-index-out-of-range')
    expect(() => serializeBoxBytesWithoutRef(box)).not.toThrow()
  })
})
