/**
 * SBox wire round-trip tests (phase 2f Stop α Task 1).
 *
 * Each fixture entry provides `bytes_hex` generated by sigma-rust's
 * `ErgoBox::sigma_serialize_bytes()`. The test:
 *   1. Decodes the hex to bytes.
 *   2. Calls `parseSValue({ tag: 'SBox' }, reader)` to parse the box.
 *   3. Calls `serializeSValue({ tag: 'SBox' }, v, writer)` to re-serialize.
 *   4. Asserts byte-for-byte equality with the original.
 *
 * Wire format (sigma-rust `chain/ergo_box.rs:202-223`):
 *   value           — VLQ u64 (BoxValue)
 *   ergo_tree_bytes — self-delimiting ErgoTree bytes (header + optional body)
 *   creation_height — VLQ u32
 *   tokens_count    — raw u8
 *   per-token       — 32-byte TokenId + VLQ u64 amount
 *   additional_regs — raw u8 count + per-register: Constant (SType + SValue)
 *   transaction_id  — 32 raw bytes
 *   index           — VLQ u16
 *
 * Cross-reference:
 *   ~/projects/sigma-rust/sigma-rust/ergotree-ir/src/chain/ergo_box.rs:202-225
 *   ~/projects/sigma-rust/sigma-rust/ergotree-ir/src/chain/ergo_box/register.rs:119-167
 *   ~/projects/sigma-rust/sigma-rust/sigma-ser/src/vlq_encode.rs (put_u16 = VLQ)
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import { parseSValue } from '../../src/wire/parse-svalue'
import { serializeSValue } from '../../src/wire/serialize-svalue'
import { ByteReader } from '../../src/wire/reader'
import { ByteWriter } from '../../src/wire/writer'

interface SboxFixtureEntry {
  name: string
  description: string
  bytes_hex: string
}

interface SboxFixture {
  entries: SboxFixtureEntry[]
}

function hexToBytes(hex: string): Uint8Array {
  const result = new Uint8Array(hex.length / 2)
  for (let i = 0; i < hex.length; i += 2) {
    result[i / 2] = parseInt(hex.slice(i, i + 2), 16)
  }
  return result
}

const fixturePath = join(
  import.meta.dirname ?? __dirname,
  '../fixtures/wire/sbox-roundtrip.json'
)
const fixture: SboxFixture = JSON.parse(readFileSync(fixturePath, 'utf8'))

describe('SBox wire round-trip', () => {
  for (const entry of fixture.entries) {
    it(`round-trips ${entry.name}: ${entry.description}`, () => {
      const original = hexToBytes(entry.bytes_hex)

      // Parse
      const reader = new ByteReader(original)
      const v = parseSValue({ tag: 'SBox' }, reader)

      // Verify fully consumed (no trailing bytes)
      expect(reader.isExhausted).toBe(true)
      expect(v.kind).toBe('Box')

      // Re-serialize
      const writer = new ByteWriter()
      serializeSValue({ tag: 'SBox' }, v, writer)
      const roundtripped = writer.toBytes()

      // Byte-for-byte equality
      expect(roundtripped).toEqual(original)
    })
  }
})
