/**
 * Per-variant wire-format roundtrip tests for structural SigmaBoolean
 * (phase 2g-medium Task 1).
 *
 * Loads fixture generated by fixture-gen/src/cmds/ergoscript/wire/sigma_boolean_variants.rs.
 * Each entry asserts:
 *  1. parseSigmaBoolean produces a structural shape equal to the Rust-generated JSON.
 *  2. serializeSigmaBoolean re-emits byte-identical bytes.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseSigmaBoolean, serializeSigmaBoolean } from '../../src/wire/sigma-boolean'
import { ByteReader } from '../../src/wire/reader'
import { ByteWriter } from '../../src/wire/writer'
import { hexToBytes } from '../_helpers'
import type { SigmaBoolean } from '../../src/mir/types'

interface VariantEntry {
  name: string
  bytes_hex: string
  structural_json: any
}

interface VariantFixture {
  description: string
  entries: VariantEntry[]
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const fixturePath = join(__dirname, '../fixtures/wire/sigma-boolean-variants.json')
const fixture: VariantFixture = JSON.parse(readFileSync(fixturePath, 'utf-8'))

/** Rehydrate fixture JSON into a runtime SigmaBoolean (for structural equality check). */
function hydrateSigmaBoolean(json: any): SigmaBoolean {
  switch (json.tag) {
    case 'TrivialProp':
      return { tag: 'TrivialProp', value: json.value as boolean }
    case 'ProveDlog':
      return { tag: 'ProveDlog', h: hexToBytes(json.h as string) }
    case 'ProveDhTuple':
      return {
        tag: 'ProveDhTuple',
        g: hexToBytes(json.g as string),
        h: hexToBytes(json.h as string),
        u: hexToBytes(json.u as string),
        v: hexToBytes(json.v as string),
      }
    case 'Cand':
      return { tag: 'Cand', items: (json.items as any[]).map(hydrateSigmaBoolean) }
    case 'Cor':
      return { tag: 'Cor', items: (json.items as any[]).map(hydrateSigmaBoolean) }
    case 'Cthreshold':
      return {
        tag: 'Cthreshold',
        k: json.k as number,
        items: (json.items as any[]).map(hydrateSigmaBoolean),
      }
    default:
      throw new Error(`hydrateSigmaBoolean: unknown tag ${json.tag}`)
  }
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false
  return true
}

function sigmaBooleanEquals(a: SigmaBoolean, b: SigmaBoolean): boolean {
  if (a.tag !== b.tag) return false
  switch (a.tag) {
    case 'TrivialProp':
      return a.value === (b as typeof a).value
    case 'ProveDlog':
      return bytesEqual(a.h, (b as typeof a).h)
    case 'ProveDhTuple': {
      const bb = b as typeof a
      return (
        bytesEqual(a.g, bb.g) &&
        bytesEqual(a.h, bb.h) &&
        bytesEqual(a.u, bb.u) &&
        bytesEqual(a.v, bb.v)
      )
    }
    case 'Cand':
    case 'Cor': {
      const bb = b as typeof a
      return (
        a.items.length === bb.items.length &&
        a.items.every((it, i) => sigmaBooleanEquals(it, bb.items[i]!))
      )
    }
    case 'Cthreshold': {
      const bb = b as typeof a
      return (
        a.k === bb.k &&
        a.items.length === bb.items.length &&
        a.items.every((it, i) => sigmaBooleanEquals(it, bb.items[i]!))
      )
    }
  }
}

describe('SigmaBoolean wire-format per-variant fixtures', () => {
  for (const entry of fixture.entries) {
    it(`${entry.name} — parse + structural-equal + round-trip`, () => {
      const bytes = hexToBytes(entry.bytes_hex)

      // Parse.
      const parsed = parseSigmaBoolean(new ByteReader(bytes))

      // Structural equality against fixture JSON.
      const expected = hydrateSigmaBoolean(entry.structural_json)
      expect(sigmaBooleanEquals(parsed, expected)).toBe(true)

      // Round-trip: serialize must emit byte-identical bytes.
      const w = new ByteWriter()
      serializeSigmaBoolean(parsed, w)
      const reserialized = w.toBytes()
      expect(bytesEqual(reserialized, bytes)).toBe(true)
    })
  }
})
