/**
 * Per-variant wire-format roundtrip tests for structural SigmaBoolean
 * (phase 2g-medium Task 1).
 *
 * Loads fixture generated by fixture-gen/src/cmds/ergoscript/wire/sigma_boolean_variants.rs.
 * Each entry asserts:
 *  1. parseSigmaBoolean produces a structural shape equal to the Rust-generated JSON.
 *  2. serializeSigmaBoolean re-emits byte-identical bytes.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  parseSigmaBoolean,
  serializeSigmaBoolean,
  SigmaBooleanParseError,
} from '../../src/wire/sigma-boolean'
import { ByteReader, ByteWriter } from '@ergots/scorex'
import { hexToBytes } from '../_helpers'
import type { SigmaBoolean } from '../../src/mir/types'

interface VariantEntry {
  name: string
  bytes_hex: string
  structural_json: any
}

interface VariantFixture {
  description: string
  entries: VariantEntry[]
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const fixturePath = join(__dirname, '../fixtures/wire/sigma-boolean-variants.json')
const fixture: VariantFixture = JSON.parse(readFileSync(fixturePath, 'utf-8'))

/** Rehydrate fixture JSON into a runtime SigmaBoolean (for structural equality check). */
function hydrateSigmaBoolean(json: any): SigmaBoolean {
  switch (json.tag) {
    case 'TrivialProp':
      return { tag: 'TrivialProp', value: json.value as boolean }
    case 'ProveDlog':
      return { tag: 'ProveDlog', h: hexToBytes(json.h as string) }
    case 'ProveDhTuple':
      return {
        tag: 'ProveDhTuple',
        g: hexToBytes(json.g as string),
        h: hexToBytes(json.h as string),
        u: hexToBytes(json.u as string),
        v: hexToBytes(json.v as string),
      }
    case 'Cand':
      return { tag: 'Cand', items: (json.items as any[]).map(hydrateSigmaBoolean) }
    case 'Cor':
      return { tag: 'Cor', items: (json.items as any[]).map(hydrateSigmaBoolean) }
    case 'Cthreshold':
      return {
        tag: 'Cthreshold',
        k: json.k as number,
        items: (json.items as any[]).map(hydrateSigmaBoolean),
      }
    default:
      throw new Error(`hydrateSigmaBoolean: unknown tag ${json.tag}`)
  }
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false
  return true
}

function sigmaBooleanEquals(a: SigmaBoolean, b: SigmaBoolean): boolean {
  if (a.tag !== b.tag) return false
  switch (a.tag) {
    case 'TrivialProp':
      return a.value === (b as typeof a).value
    case 'ProveDlog':
      return bytesEqual(a.h, (b as typeof a).h)
    case 'ProveDhTuple': {
      const bb = b as typeof a
      return (
        bytesEqual(a.g, bb.g) &&
        bytesEqual(a.h, bb.h) &&
        bytesEqual(a.u, bb.u) &&
        bytesEqual(a.v, bb.v)
      )
    }
    case 'Cand':
    case 'Cor': {
      const bb = b as typeof a
      return (
        a.items.length === bb.items.length &&
        a.items.every((it, i) => sigmaBooleanEquals(it, bb.items[i]!))
      )
    }
    case 'Cthreshold': {
      const bb = b as typeof a
      return (
        a.k === bb.k &&
        a.items.length === bb.items.length &&
        a.items.every((it, i) => sigmaBooleanEquals(it, bb.items[i]!))
      )
    }
    default: {
      const _exhaust: never = a
      throw new Error(`sigmaBooleanEquals: unhandled tag ${(_exhaust as { tag: string }).tag}`)
    }
  }
}

describe('SigmaBoolean wire-format per-variant fixtures', () => {
  for (const entry of fixture.entries) {
    it(`${entry.name} — parse + structural-equal + round-trip`, () => {
      const bytes = hexToBytes(entry.bytes_hex)

      // Parse.
      const parsed = parseSigmaBoolean(new ByteReader(bytes))

      // Structural equality against fixture JSON.
      const expected = hydrateSigmaBoolean(entry.structural_json)
      expect(sigmaBooleanEquals(parsed, expected)).toBe(true)

      // Round-trip: serialize must emit byte-identical bytes.
      const w = new ByteWriter()
      serializeSigmaBoolean(parsed, w)
      const reserialized = w.toBytes()
      expect(bytesEqual(reserialized, bytes)).toBe(true)
    })
  }
})

// ---------------------------------------------------------------------------
// F5 batch 4 (member D part 2) — GE canonical-bytes invariant at SigmaBoolean
// leaf points (ProveDlog.h, ProveDhTuple g/h/u/v).
//
// JVM verdict: these leaves parse through the same GroupElementSerializer as
// GE data values — SigmaBoolean.scala:36-44 (ProveDlogSerializer /
// ProveDHTupleSerializer wiring) and :71-80 (parse dispatch), each serializer
// delegating to GroupElementSerializer.parse (ProveDlogSerializer.scala:12-15,
// ProveDHTupleSerializer.scala:17-23). So: 0x00-lead → identity POINT (tail
// discarded, re-serializes as 33 zeros); invalid non-0x00-lead → throw.
//
// Contract: facts/ergoscript-sigma.md "GE canonical-bytes" invariant bullet;
// facts/ergoscript-wire.md `'ec-point-invalid'` taxonomy entry.
// ---------------------------------------------------------------------------

// secp256k1 generator G, SEC1 compressed (valid point).
const GENERATOR_HEX = '0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'
// x = 2^256 - 1 > field prime p → not a curve point; JVM decodePoint throws.
const INVALID_X = '02' + 'ff'.repeat(32)
// 0x00-lead with garbage tail: JVM parses to the identity POINT, tail discarded.
const GARBAGE_IDENTITY = '00' + 'aa'.repeat(32)
// Canonical identity encoding (what the JVM serializer emits for infinity).
const CANONICAL_IDENTITY = '00'.repeat(33)

const OP_PROVE_DLOG_HEX = 'cd'
const OP_PROVE_DH_TUPLE_HEX = 'ce'

describe('SigmaBoolean leaf EC points — GE canonical-bytes invariant (F5 batch 4)', () => {
  it('ProveDlog with x-not-on-curve h rejects with ec-point-invalid', () => {
    const bytes = hexToBytes(OP_PROVE_DLOG_HEX + INVALID_X)
    expect(() => parseSigmaBoolean(new ByteReader(bytes))).toThrow(
      expect.objectContaining({
        name: 'SigmaBooleanParseError',
        code: 'ec-point-invalid',
      })
    )
    expect(() => parseSigmaBoolean(new ByteReader(bytes))).toThrow(SigmaBooleanParseError)
  })

  it('ProveDlog with 0x00-lead garbage-tail h normalizes to the canonical identity', () => {
    const bytes = hexToBytes(OP_PROVE_DLOG_HEX + GARBAGE_IDENTITY)
    const parsed = parseSigmaBoolean(new ByteReader(bytes))
    expect(parsed.tag).toBe('ProveDlog')
    if (parsed.tag !== 'ProveDlog') throw new Error('unreachable')
    expect(parsed.h).toEqual(hexToBytes(CANONICAL_IDENTITY))

    // Carve-out 3: re-serialization emits the CANONICAL identity (≠ garbage
    // input) — same as the JVM value layer, which re-serializes the POINT.
    const w = new ByteWriter()
    serializeSigmaBoolean(parsed, w)
    expect(w.toBytes()).toEqual(hexToBytes(OP_PROVE_DLOG_HEX + CANONICAL_IDENTITY))
  })

  it('ProveDhTuple with one invalid leg (u) rejects with ec-point-invalid, naming the field', () => {
    const bytes = hexToBytes(
      OP_PROVE_DH_TUPLE_HEX + GENERATOR_HEX + GENERATOR_HEX + INVALID_X + GENERATOR_HEX
    )
    expect(() => parseSigmaBoolean(new ByteReader(bytes))).toThrow(
      expect.objectContaining({
        name: 'SigmaBooleanParseError',
        code: 'ec-point-invalid',
        message: expect.stringContaining('ProveDhTuple.u'),
      })
    )
  })
})

// ---------------------------------------------------------------------------
// Task 4B (2026-09-28) — CTHRESHOLD's k and n checks move to where the JVM
// makes them (SigmaBoolean.scala:94-100, the AtLeastCode parse arm; :220-224,
// the CTHRESHOLD case class's `require`). The JVM reads k, then n, each a
// getUShort (hard above 0xFFFF as it is read); only THEN does it read the n
// children; only after that does `CTHRESHOLD(k, children)`'s constructor run
// its require(k >= 0 && k <= children.length && children.length <= 255).
// ---------------------------------------------------------------------------

describe('CTHRESHOLD in the JVM order (SigmaBoolean.scala:94-100, :223)', () => {
  const codeOf = (bytes: number[]) => { try { parseSigmaBoolean(new ByteReader(Uint8Array.from(bytes))); return 'no-throw' } catch (e) { return (e as { code?: string }).code } }
  const codeOfWindowed = (bytes: number[], positionLimit: number) => {
    const r = new ByteReader(Uint8Array.from(bytes))
    r.positionLimit = positionLimit
    try { parseSigmaBoolean(r); return 'no-throw' } catch (e) { return (e as { code?: string }).code }
  }
  it('k above 0xFFFF rejects before n is read', () => {
    expect(codeOf([0x98, 0x80, 0x80, 0x04])).toBe('cthreshold-k-out-of-range')   // k = 0x10000, nothing after
  })
  it('k > n is checked after the children', () => {
    expect(codeOf([0x98, 0x02, 0x01])).toBe('truncated')   // k=2 n=1, the child read runs out first
  })
  it('more than 255 children rejects after the children', () => {
    expect(codeOf([0x98, 0x01, 0x80, 0x02, ...new Array(256).fill(0xd3)])).toBe('arity-out-of-range')
  })

  // Ruling (task-4B, "Context the brief cannot know", 2026-09-28): ergots' own
  // stricter-than-JVM k < 1 check is placed AFTER the children are read, not
  // before. The JVM's own require (k >= 0 …) already runs only after the
  // children (the require lives in the CTHRESHOLD constructor, called with the
  // already-read children array); placing ergots' extra, stricter check any
  // earlier would let a hard k-reject pre-empt a window error a child read
  // would otherwise hit first — turning a rule-1014 degrade (that the JVM
  // takes) into a hard ergots-only reject, which widens the tracked k=0
  // divergence into sized-tree window cases too. Bytes: opcode(0x98) k=0x00
  // n=0x01 child-opcode=0xd3, with positionLimit=2 so the child's opcode read
  // (at position 3) begins past the window.
  it('k = 0 with a child past the window hits the window error, not the stricter-than-JVM k check', () => {
    expect(codeOfWindowed([0x98, 0x00, 0x01, 0xd3], 2)).toBe('position-limit-exceeded')
  })

  // Companion: the same bytes with no window reach ergots' own stricter verdict.
  // The JVM itself accepts k=0 outright (`require(k >= 0 …)`); this reject is a
  // tracked follow-up (verifier semantics for empty/trivial conjectures), not a
  // JVM-mirrored one.
  it('the same k=0 bytes with no window give the stricter-than-JVM cthreshold-k-out-of-range', () => {
    expect(codeOf([0x98, 0x00, 0x01, 0xd3])).toBe('cthreshold-k-out-of-range')
  })
})
