/**
 * SHeader SValue ErgoTree wire round-trip tests.
 *
 * Phase 2h-c.1 Step 5 (Task 5.1.2). Validates that
 * `serializeTree(parseTree(bytes)) === bytes` holds byte-for-byte for
 * V3 ErgoTrees whose segregated-constants section contains SHeader
 * literals (single, Coll, Option variants).
 *
 * Also validates that a V2 tree with an embedded SHeader type in the
 * constants section is rejected by parseTree with the typed error
 * `sheader-tree-version-too-low`.
 *
 * Fixtures (binary) generated by fixture-gen sheader_constants.rs:
 *   sheader-constants-v3-single-header.bin    — V3, 1 SHeader (V2 mainnet)
 *   sheader-constants-v3-single-v1-header.bin — V3, 1 SHeader (V1 synthetic)
 *   sheader-constants-v3-coll-of-headers.bin  — V3, Coll[Header] of 3 entries
 *   sheader-constants-v3-option-some.bin      — V3, Option[Header] = Some
 *   sheader-constants-v3-option-none.bin      — V3, Option[Header] = None
 *   sheader-constants-v2-header-literal.bin   — V2, SHeader (negative fixture)
 *
 * Cross-reference:
 *   sigma-rust `ergotree-ir/src/serialization/data.rs:98,196`
 *   TS `packages/ergoscript/src/wire/ergo-tree.ts`
 *   TS `packages/ergoscript/src/wire/parse-svalue.ts` (sheader arm, line ~385)
 */

import { describe, expect, test } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseTree, serializeTree } from '../../src/wire/ergo-tree'
import { SValueParseError } from '../../src/wire/parse-svalue'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const FIXTURE_DIR = join(__dirname, '../fixtures/wire')

function loadFixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURE_DIR, `${name}.bin`)))
}

const POSITIVE_FIXTURES = [
  'sheader-constants-v3-single-header',
  'sheader-constants-v3-single-v1-header',
  'sheader-constants-v3-coll-of-headers',
  'sheader-constants-v3-option-some',
  'sheader-constants-v3-option-none',
] as const

describe('SHeader SValue wire round-trip — V3 trees', () => {
  test.each(POSITIVE_FIXTURES)('%s round-trips byte-equal', (name) => {
    const bytes = loadFixture(name)
    const tree = parseTree(bytes)
    const out = serializeTree(tree)
    expect(out).toEqual(bytes)
  })
})

describe('SHeader SValue wire — V<3 rejection', () => {
  test('V2 tree with SHeader constant throws sheader-tree-version-too-low', () => {
    const bytes = loadFixture('sheader-constants-v2-header-literal')
    expect(() => parseTree(bytes)).toThrow(
      expect.objectContaining({ code: 'sheader-tree-version-too-low' })
    )
    expect(() => parseTree(bytes)).toThrow(SValueParseError)
  })
})
