/**
 * SHeader SValue ErgoTree wire round-trip tests.
 *
 * Phase 2h-c.1 Step 5 (Task 5.1.2). Validates that
 * `serializeTree(parseTree(bytes)) === bytes` holds byte-for-byte for
 * V3 ErgoTrees whose segregated-constants section contains SHeader
 * literals (single, Coll, Option variants).
 *
 * Also validates that a V2 tree with an embedded SHeader type in the
 * constants section is rejected by parseTree with the typed error
 * `sheader-tree-version-too-low`.
 *
 * Fixtures (binary) generated by fixture-gen sheader_constants.rs:
 *   sheader-constants-v3-single-header.bin    — V3, 1 SHeader (V2 mainnet)
 *   sheader-constants-v3-single-v1-header.bin — V3, 1 SHeader (V1 synthetic)
 *   sheader-constants-v3-coll-of-headers.bin  — V3, Coll[Header] of 3 entries
 *   sheader-constants-v3-option-some.bin      — V3, Option[Header] = Some
 *   sheader-constants-v3-option-none.bin      — V3, Option[Header] = None
 *   sheader-constants-v2-header-literal.bin   — V2, SHeader (negative fixture)
 *
 * Cross-reference:
 *   sigma-rust `ergotree-ir/src/serialization/data.rs:98,196`
 *   TS `packages/ergoscript/src/wire/ergo-tree.ts`
 *   TS `packages/ergoscript/src/wire/parse-svalue.ts` (sheader arm, line ~385)
 */

import { describe, expect, test, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ByteReader, ByteWriter } from '@ergots/scorex'
import { parseTree, serializeTree } from '../../src/wire/ergo-tree'
import { parseSValue, SValueParseError } from '../../src/wire/parse-svalue'
import { serializeSValue } from '../../src/wire/serialize-svalue'
import type { ParsedErgoTree } from '../../src/mir/types'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const FIXTURE_DIR = join(__dirname, '../fixtures/wire')

function loadFixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURE_DIR, `${name}.bin`)))
}

const POSITIVE_FIXTURES = [
  'sheader-constants-v3-single-header',
  'sheader-constants-v3-single-v1-header',
  'sheader-constants-v3-coll-of-headers',
  'sheader-constants-v3-option-some',
  'sheader-constants-v3-option-none',
] as const

describe('SHeader SValue wire round-trip — V3 trees', () => {
  test.each(POSITIVE_FIXTURES)('%s round-trips byte-equal', (name) => {
    const bytes = loadFixture(name)
    const tree = parseTree(bytes)
    const out = serializeTree(tree)
    expect(out).toEqual(bytes)
  })
})

describe('SHeader SValue wire — V<3 rejection (NOT soft-fork-degradable)', () => {
  test('V2 tree with SHeader constant throws sheader-tree-version-too-low', () => {
    const bytes = loadFixture('sheader-constants-v2-header-literal')
    // Unlike SOption, SHeader (typeCode 104) is NOT special-cased by JVM rule 1009
    // (CheckSerializableTypeCode) and is NOT > LastDataType (111), so rule 1009 does NOT
    // throw a ValidationException for it — the JVM falls through to a DIRECT SerializerException
    // (CoreDataSerializer.scala:146) which ESCAPES the UnparsedErgoTree fallback → the tree
    // REJECTS even though it is size-flagged. So ergots must NOT degrade this to Unparsed.
    expect(() => parseTree(bytes)).toThrow(
      expect.objectContaining({ code: 'sheader-tree-version-too-low' })
    )
    expect(() => parseTree(bytes)).toThrow(SValueParseError)
  })
})

it('an invalid minerPk rejects as it is read, before the next read trips the window', () => {
  // A valid v2 header's SValue bytes, taken from the file's existing fixture.
  const tree = parseTree(loadFixture('sheader-constants-v3-single-header')) as ParsedErgoTree
  const hdr = tree.constants[0]!
  const w = new ByteWriter(); serializeSValue({ tag: 'SHeader' }, hdr, 3, w)
  const good = w.toBytes()
  const pk = (hdr as unknown as { value: { autolykosSolution: { minerPk: Uint8Array } } }).value.autolykosSolution.minerPk
  // Structural offset, not a byte search: a v2 AutolykosSolution is exactly
  // [minerPk: 33][nonce: 8] with nothing after, so minerPk's lead byte sits
  // `NONCE_LEN + minerPk.length` before the end. A byte-pattern search for
  // `pk` (33 zero bytes — this fixture's minerPk is the canonical identity)
  // is NOT reliable here: several PRECEDING header fields (parentId,
  // adProofsRoot, ...) are also zero-filled placeholders in this fixture, so
  // a forward search matches inside one of those, and a backward search
  // matches 3 bytes late by borrowing nonce's own leading zero bytes —
  // either way landing away from offset 0 of minerPk, the one byte
  // `canonicalGePayload` actually inspects for a 0x00-lead point (bytes
  // 1..32 are never inspected), so the mutation below would silently land on
  // an ignored byte and the point would still parse as identity.
  const NONCE_LEN = 8
  const at = good.length - NONCE_LEN - pk.length
  expect(good.slice(at, at + pk.length)).toEqual(pk) // sanity: offset lands exactly on minerPk
  const bad = good.slice(); bad[at] = 0x05        // not a valid compressed-point prefix
  const r = new ByteReader(bad); r.positionLimit = at + 32   // the next read (the nonce) is past the window
  let code: string | undefined
  try { parseSValue({ tag: 'SHeader' }, 3, r) } catch (e) { code = (e as { code?: string }).code }
  expect(code).toBe('group-element-invalid-point')
})
