/**
 * `verifySignature` fixture-driven tests (phase 2g-medium Task 6).
 *
 * Three suites, all loading fixtures generated by
 * `fixture-gen/src/cmds/ergoscript/verify/`:
 *
 *  - V1 positive: real (sb, msg, sig) triples — must verify true.
 *  - V1 reject + malformed: TrivialProp short-circuits, conjecture inputs,
 *    empty / truncated proofs — exact outcome dictated by fixture.
 *  - V2 mutation: 56 byte-flip mutations of a baseline ProveDlog proof —
 *    must return false or throw VerifyError; returning true is a vulnerability.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { verifySignature } from '../../src/sigma/verifier'
import { VerifyError } from '../../src/sigma/errors'
import { hexToBytes } from '../_helpers'
import type { SigmaBoolean } from '../../src/mir/types'

interface PositiveEntry {
  name: string
  sigma_boolean_json: any
  message_hex: string
  signature_hex: string
  expected_result: boolean
}

interface RejectEntry {
  name: string
  sigma_boolean_json: any
  message_hex: string
  signature_hex: string
  expected_outcome: string
}

interface MutationEntry {
  name: string
  sigma_boolean_json: any
  message_hex: string
  mutated_signature_hex: string
  flip_offset: number
  expected_outcome: string
}

/** Rehydrate fixture JSON into a runtime SigmaBoolean (mirrors Task 1 hydrator). */
function hydrateSigmaBoolean(json: any): SigmaBoolean {
  switch (json.tag) {
    case 'TrivialProp':
      return { tag: 'TrivialProp', value: json.value as boolean }
    case 'ProveDlog':
      return { tag: 'ProveDlog', h: hexToBytes(json.h as string) }
    case 'ProveDhTuple':
      return {
        tag: 'ProveDhTuple',
        g: hexToBytes(json.g as string),
        h: hexToBytes(json.h as string),
        u: hexToBytes(json.u as string),
        v: hexToBytes(json.v as string),
      }
    case 'Cand':
      return { tag: 'Cand', items: (json.items as any[]).map(hydrateSigmaBoolean) }
    case 'Cor':
      return { tag: 'Cor', items: (json.items as any[]).map(hydrateSigmaBoolean) }
    case 'Cthreshold':
      return {
        tag: 'Cthreshold',
        k: json.k as number,
        items: (json.items as any[]).map(hydrateSigmaBoolean),
      }
    default:
      throw new Error(`hydrateSigmaBoolean: unknown tag ${json.tag}`)
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url))

const positiveFixture = JSON.parse(
  readFileSync(join(__dirname, '../fixtures/verify/verifier-positive.json'), 'utf-8')
) as { description: string; entries: PositiveEntry[] }

const rejectFixture = JSON.parse(
  readFileSync(join(__dirname, '../fixtures/verify/verifier-reject.json'), 'utf-8')
) as { description: string; entries: RejectEntry[] }

const mutationFixture = JSON.parse(
  readFileSync(join(__dirname, '../fixtures/verify/verifier-mutation.json'), 'utf-8')
) as { description: string; baseline_signature_hex: string; entries: MutationEntry[] }

describe('verifySignature — V1 positive', () => {
  for (const entry of positiveFixture.entries) {
    it(`${entry.name} — verifies`, () => {
      const sb = hydrateSigmaBoolean(entry.sigma_boolean_json)
      const msg = hexToBytes(entry.message_hex)
      const sig = hexToBytes(entry.signature_hex)
      expect(verifySignature(sb, msg, sig)).toBe(true)
    })
  }
})

describe('verifySignature — V1 reject + malformed', () => {
  for (const entry of rejectFixture.entries) {
    it(`${entry.name} — ${entry.expected_outcome}`, () => {
      const sb = hydrateSigmaBoolean(entry.sigma_boolean_json)
      const msg = hexToBytes(entry.message_hex)
      const sig = hexToBytes(entry.signature_hex)
      switch (entry.expected_outcome) {
        case 'returns-true':
          expect(verifySignature(sb, msg, sig)).toBe(true)
          break
        case 'returns-false':
          expect(verifySignature(sb, msg, sig)).toBe(false)
          break
        default: {
          // expected_outcome is a VerifyError code
          let captured: unknown = null
          try {
            verifySignature(sb, msg, sig)
          } catch (e) {
            captured = e
          }
          expect(captured).toBeInstanceOf(VerifyError)
          expect((captured as VerifyError).code).toBe(entry.expected_outcome)
        }
      }
    })
  }
})

describe('verifySignature — V2 mutation', () => {
  for (const entry of mutationFixture.entries) {
    it(`${entry.name} (offset ${entry.flip_offset}) — rejects`, () => {
      const sb = hydrateSigmaBoolean(entry.sigma_boolean_json)
      const msg = hexToBytes(entry.message_hex)
      const sig = hexToBytes(entry.mutated_signature_hex)
      // The verifier must EITHER return false OR throw VerifyError.
      // The only forbidden outcome is returning true.
      try {
        const result = verifySignature(sb, msg, sig)
        // If we reach here, the verifier returned a boolean — must be false.
        if (result === true) {
          throw new Error(
            `mutation at offset ${entry.flip_offset} passed verification — verifier vulnerability!`
          )
        }
        expect(result).toBe(false)
      } catch (e) {
        if (e instanceof VerifyError) {
          // Acceptable — typed error during parse / scalar bounds / etc.
          return
        }
        throw e
      }
    })
  }
})
