import { describe, it, test, expect } from 'vitest';
import { prove, proveWithReader } from '../src/prover.ts';
import { serializeProof, parseProof } from '../src/proof.ts';
import { verifyParsedProof } from '../src/verifier.ts';
import { heightsForNextRecalculation } from '../src/difficulty.ts';
import { ProofVerificationError } from '../src/errors.ts';
import { MemoryReader } from './reader-double.ts';
import { buildTestChain, bytesToHex } from './helpers.ts';

const SHAPES: [number[], number, number][] = [
  [[0, 0, 1, 0, 2, 0, 1, 0], 1, 1],
  [[0, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0], 2, 2],
  [[0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 0, 1, 0], 2, 3],
  [[0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 4, 0, 0, 1, 0, 2], 3, 4],
];

describe('proveWithReader equivalence with prove()', () => {
  // proveWithReader (JVM NipopowProverWithDbAlgs.prove) and prove() (JVM
  // NipopowAlgos.prove) are NOT byte-identical in general — a real property
  // of the two JVM source algorithms, not a TS-port bug. Two mechanisms
  // (both confirmed against JVM source; full detail + hand-verified trace
  // in task-8-report.md):
  //
  //  1. No walk position for "level 0": `linksWithIndexes` = `interlinks.tail
  //     .reverse.zipWithIndex` only ever produces positions for levels >= 1
  //     (level >= 0 is trivially every block via plain parent-child
  //     adjacency, so no interlink position represents it). NipopowAlgos
  //     .prove's explicit `level = 0` pass sweeps every header from the
  //     anchor onward regardless of interlink connectivity — but a run of
  //     consecutive level-0 blocks whose id is never recorded in any later
  //     block's interlinks (updateInterlinks only records a PARENT's id when
  //     the parent's own level >= 1) is structurally undiscoverable by
  //     proveWithReader's walk.
  //  2. Genesis "free credit": NipopowAlgos.scala's provePrefix filters
  //     `chain.dropRight(k)` by `maxLevelOf(h) >= level && h.height >=
  //     anchoringPoint.height`. Genesis (maxLevelOf = Int.MaxValue, height =
  //     1) trivially satisfies this at EVERY level until the anchor first
  //     advances past height 1 — a "free" +1 with no walk-side counterpart
  //     (genesis is never present in any header's interlinks TAIL). When the
  //     *true* (non-genesis) count at a level equals exactly `m`, the
  //     narrowing decision can flip between the two algorithms.
  //
  // WHICH CHAINS THIS BITES (get this right — the previous version of this
  // comment had it backwards): mechanism 1 fires on any chain with a level-0
  // header in [final anchor, suffixHead) — i.e. essentially every REAL
  // chain. KMZ17 expects level mu with probability 2^-mu, so ~half of all
  // real blocks are level 0; a captured 21-header mainnet sample has 15/20
  // parents at level 0 (facts/nipopow.md). It does NOT fire on the SANTA
  // fixtures below or the JVM's own genChain(3000) equivalence test
  // (PoPowAlgosWithDBSpec.scala) — both are generated under a fake PoW
  // scheme (DefaultFakePowScheme, powType = "fake") whose level sequence is
  // monotonically non-decreasing with ZERO level-0 headers past genesis
  // (verified directly against both committed SANTA chains: 0/31 and 0/63).
  // That's an artifact of the fake scheme, not representative of real
  // mining — "byte-identical on realistic chains" is exactly backwards:
  // byte-identity holds on the *unrealistic* level-0-free chains and is
  // violated systematically on real ones.
  //
  // WHICH ALGORITHM IS PRODUCTION: proveWithReader (NipopowProverWithDbAlgs)
  // is what a real JVM node actually serves — PopowProcessor.scala's
  // popowProof calls it directly, backing the live GET
  // /nipopow/proof/{m}/{k} REST endpoint. prove() (NipopowAlgos.prove)
  // carries the JVM's own comment marking it the non-production variant:
  // "Paper-like code used in tests only" (NipopowAlgos.scala:127). None of
  // prover-santa.test.ts's SANTA vectors are NipopowProverWithDbAlgs ground
  // truth either — all 8 were generated by calling NipopowAlgos.prove (on
  // the full chain for tip cases, on a truncated chain for the anchored
  // case); the byte match there demonstrates agreement on these specific
  // level-0-free chains, which is expected given mechanism 1, not general
  // cross-algorithm equivalence. The actual NipopowProverWithDbAlgs
  // ground-truth anchor is Task 9's live-node walk.
  //
  // The SHAPES chains below deliberately include level-0 headers (unlike
  // the SANTA fixtures), so they DO trip both mechanisms — closer to how a
  // real chain behaves than the fake-PoW fixtures are. GOLDEN_PREFIX_HEIGHTS
  // is captured from the actual implementation: SHAPES[0] (the smallest) is
  // hand-verified step-by-step in task-8-report.md; all four are
  // corroborated by prover-santa.test.ts's anchored byte-match (same
  // collectLevel/foldRight/dedupe logic, real ground truth, just on a
  // level-0-free chain) and the structural KMZ17 invariants asserted below.
  const GOLDEN_PREFIX_HEIGHTS: number[][] = [
    [1, 3, 5, 7],
    [1, 3, 5, 7, 9],
    [1, 4, 8, 10, 12],
    [1, 4, 8, 10, 12, 15, 17, 19],
  ];
  for (const [i, [levels, m, k]] of SHAPES.entries()) {
    it(`levels[${levels.length}] m=${m} k=${k}: suffix matches prove(), prefix matches the pinned walk selection`, async () => {
      const chain = buildTestChain(levels);
      const fromMemory = await proveWithReader(new MemoryReader(chain), { m, k });
      const direct = prove(chain, { m, k });

      // Suffix selection never depends on the prefix-construction algorithm —
      // both algorithms take the suffix straight from the chain/reader.
      expect(bytesToHex(fromMemory.suffixHead.header.id)).toBe(bytesToHex(direct.suffixHead.header.id));
      expect(fromMemory.suffixTail.map(h => bytesToHex(h.id))).toEqual(direct.suffixTail.map(h => bytesToHex(h.id)));

      // Pinned prefix-selection regression guard — see block comment above.
      expect(fromMemory.prefix.map(p => p.header.height)).toEqual(GOLDEN_PREFIX_HEIGHTS[i]);

      // proveWithReader's own output is a structurally valid, well-formed proof
      // (mirrors prover.test.ts's "prove() selection" invariant checks).
      const result = verifyParsedProof(fromMemory, { checkPoW: false });
      expect(result.totalHeaders).toBe(fromMemory.prefix.length + 1 + fromMemory.suffixTail.length);
      const bytes = serializeProof(fromMemory);
      expect(bytesToHex(serializeProof(parseProof(bytes)))).toBe(bytesToHex(bytes));

      const hs = fromMemory.prefix.map(p => p.header.height);
      expect([...new Set(hs)].sort((a, b) => a - b)).toEqual(hs); // strictly ascending, deduped
      expect(Math.max(...hs)).toBeLessThan(fromMemory.suffixHead.header.height);
      expect(hs[0]).toBe(1); // genesis anchored
    });
  }

  it('anchored mode: headerId mid-chain ≡ proveWithReader tip-mode on the truncated chain', async () => {
    // Oracle is proveWithReader itself (same algorithm), not prove() — see the
    // block comment above: cross-algorithm byte-identity is not guaranteed on
    // arbitrary chains, only same-algorithm self-consistency is. This asserts
    // the property that IS always true: anchored suffix selection against the
    // full reader walks the same interlink graph as tip-mode against a reader
    // truncated exactly past the anchor's k-suffix (the backward-only walk from
    // suffixHead can never observe anything past it regardless of what else the
    // reader holds).
    const [levels, m, k] = SHAPES[3]!;
    const chain = buildTestChain(levels);
    const anchorIdx = chain.length - 1 - 4; // suffixHead 4 from tip
    const anchorId = chain[anchorIdx]!.header.id;
    const anchored = await proveWithReader(new MemoryReader(chain), { m, k }, anchorId);
    expect(anchored.suffixHead.header.height).toBe(anchorIdx + 1);
    const truncated = chain.slice(0, anchorIdx + k); // suffix = anchor + k-1 after it
    const tipOnTruncated = await proveWithReader(new MemoryReader(truncated), { m, k });
    expect(bytesToHex(serializeProof(anchored)))
      .toBe(bytesToHex(serializeProof(tipOnTruncated)));
  });
});

describe('proveWithReader errors + load bound', () => {
  it('gates: invalid-m / invalid-k / chain-too-short', async () => {
    const chain = buildTestChain([0, 0, 1, 0]);
    await expect(proveWithReader(new MemoryReader(chain), { m: 0, k: 1 })).rejects.toMatchObject({ code: 'invalid-m' });
    await expect(proveWithReader(new MemoryReader(chain), { m: 1, k: 0 })).rejects.toMatchObject({ code: 'invalid-k' });
    await expect(proveWithReader(new MemoryReader(chain), { m: 3, k: 2 })).rejects.toMatchObject({ code: 'chain-too-short' });
  });

  it('missing header → missing-popow-header', async () => {
    const chain = buildTestChain(SHAPES[1]![0]);
    const reader = new MemoryReader(chain);
    reader.popowHeaderAtHeight = async () => { reader.calls++; return null; }; // genesis fetch dies
    await expect(proveWithReader(reader, { m: 2, k: 2 })).rejects.toMatchObject({ code: 'missing-popow-header' });
  });

  it('load count ≪ N (no accidental full scan)', async () => {
    const levels = Array.from({ length: 120 }, (_, i) => [0, 0, 1, 0, 2, 0, 1, 0, 3, 0][i % 10]!);
    const chain = buildTestChain(levels);
    const reader = new MemoryReader(chain);
    const m = 3, k = 3;
    await proveWithReader(reader, { m, k });
    // Loose bound: c·(m + k + m·log2 N) with c = 6 — fails hard on O(N).
    const bound = 6 * (m + k + m * Math.log2(chain.length));
    expect(reader.calls).toBeLessThan(bound);
    expect(reader.calls).toBeLessThan(chain.length); // and strictly under N
  });
});

describe('proveWithReader continuous mode (e=16, u=8)', () => {
  // 64-header level-0-free-ish chain; exact levels don't matter for injection.
  const levels = Array.from({ length: 64 }, (_, i) => (i % 8 === 7 ? 2 : 1));
  const E = { epochLength: 16, useLastEpochs: 8 };

  test('injects exactly the gated needed heights and verifies end-to-end', async () => {
    const chain = buildTestChain(levels);
    const reader = new MemoryReader(chain);
    const proof = await proveWithReader(reader, { m: 3, k: 3, continuous: true, ...E });

    expect(proof.continuous).toBe(true);
    const sh = proof.suffixHead.header.height; // tip-mode: 64 - k + 1 = 62
    const needed = heightsForNextRecalculation(sh, 16, 8).filter(h => h > 0 && h < sh);
    const prefixHeights = new Set(proof.prefix.map(p => p.header.height));
    for (const h of needed) expect(prefixHeights.has(h), `height ${h}`).toBe(true);

    // strictly increasing prefix (dedupe + sort held under injection)
    const hs = proof.prefix.map(p => p.header.height);
    for (let i = 1; i < hs.length; i++) expect(hs[i]!).toBeGreaterThan(hs[i - 1]!);

    // the unit's promise: what the prover builds, the verifier accepts
    const result = verifyParsedProof(proof, { checkPoW: false, ...E });
    expect(result.continuous).toBe(true);
  });

  test('continuous=false output is byte-region-identical to the pre-0.4.0 shape (flag default false)', async () => {
    const chain = buildTestChain(levels);
    const a = await proveWithReader(new MemoryReader(chain), { m: 3, k: 3 });
    const b = await proveWithReader(new MemoryReader(chain), { m: 3, k: 3, continuous: false, ...E });
    expect(a.continuous).toBe(false);
    expect(a.prefix.map(p => p.header.height)).toEqual(b.prefix.map(p => p.header.height));
  });

  test('reader missing a needed height: silently skipped, proof then fails verification', async () => {
    // Deliberately NOT the shared level-0-free `levels` chain used by the other
    // three tests in this block: on that chain every needed difficulty height
    // (multiple of epochLength=16) is also a superblock marker (multiple of the
    // chain's own 8-height superblock spacing), which the walk's higher-level
    // pass discovers unconditionally, for any m — so on that chain NO needed
    // height is ever absent from the non-continuous prefix and this test cannot
    // demonstrate "silently skipped" at all (verified empirically: for m in
    // 1..10 every one of needed=[16,32,48] is already walk-selected). This
    // motif (same one used by SHAPES[2] above) has genuine level-0 gaps, so the
    // walk's own selection legitimately omits some heights, leaving room for
    // the injection to matter.
    const motif = [0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 0, 1, 0];
    const sparseLevels = Array.from({ length: 64 }, (_, i) => motif[i % motif.length]!);
    const chain = buildTestChain(sparseLevels);
    const sh = 62;
    const needed = heightsForNextRecalculation(sh, 16, 8).filter(h => h > 0 && h < sh);
    const dropped = needed[0]!;
    class GappyReader extends MemoryReader {
      override async popowHeaderAtHeight(h: number) {
        return h === dropped ? null : super.popowHeaderAtHeight(h);
      }
    }
    const proof = await proveWithReader(new GappyReader(chain), { m: 3, k: 3, continuous: true, ...E });
    expect(proof.continuous).toBe(true);
    expect(proof.prefix.some(p => p.header.height === dropped)).toBe(false);
    // If a future change to buildTestChain/the walk makes needed[0] walk-selected
    // again on this chain too, pick the first needed height NOT in the
    // non-continuous proof's prefix instead (see block comment above for why
    // that alone isn't always sufficient — the chain shape matters more).
    try {
      verifyParsedProof(proof, { checkPoW: false, ...E });
      throw new Error('expected throw');
    } catch (e) {
      expect((e as ProofVerificationError).code).toBe('missing-difficulty-headers');
    }
  });

  test('bad difficulty params throw RangeError even with continuous=false (JVM constructs DifficultyAdjustment unconditionally)', async () => {
    const chain = buildTestChain(levels);
    await expect(
      proveWithReader(new MemoryReader(chain), { m: 3, k: 3, epochLength: 0 }),
    ).rejects.toThrow(RangeError);
  });
});
