/**
 * Prover fixture tests — byte-for-byte comparison against Rust BatchAVLProver.
 *
 * Fixtures generated by the preserved emitter at test/fixtures/prover/EMITTER.rs
 * (see its header for the regeneration recipe).
 * Each fixture specifies a tree config, operation sequence, generateProof()
 * trigger points, and expected proof bytes + digests from the Rust prover.
 *
 * The TS BatchAVLProver must produce byte-identical output for identical input.
 */

import { describe, it, expect } from 'vitest'
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { BatchAVLProver } from '../src/batch-prover.js'
import type { Operation } from '../src/index.js'

// ---------------------------------------------------------------------------
// Fixture types
// ---------------------------------------------------------------------------

interface FixtureOp {
  tag: string
  keyHex: string
  valueHex?: string
  delta?: number
}

interface Fixture {
  name: string
  config: {
    keyLength: number
    valueLengthOpt: number | null
  }
  operations: FixtureOp[]
  genProofAfter: number[]
  expectedProofs: string[]
  expectedDigests: string[]
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function hexToBytes(hex: string): Uint8Array {
  const len = hex.length / 2
  const out = new Uint8Array(len)
  for (let i = 0; i < len; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16)
  }
  return out
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

function jsonToOp(op: FixtureOp): Operation {
  const key = hexToBytes(op.keyHex)
  switch (op.tag) {
    case 'Insert':
      return { tag: 'Insert', key, value: hexToBytes(op.valueHex!) }
    case 'Update':
      return { tag: 'Update', key, value: hexToBytes(op.valueHex!) }
    case 'Remove':
      return { tag: 'Remove', key }
    case 'Lookup':
      return { tag: 'Lookup', key }
    case 'InsertOrUpdate':
      return { tag: 'InsertOrUpdate', key, value: hexToBytes(op.valueHex!) }
    case 'RemoveIfExists':
      return { tag: 'RemoveIfExists', key }
    case 'UpdateLongBy': {
      return { tag: 'UpdateLongBy', key, delta: BigInt(op.delta!) }
    }
    case 'UnknownModification':
      return { tag: 'UnknownModification', key }
    default:
      throw new Error(`Unknown op tag: ${op.tag}`)
  }
}

function loadFixtures(): Fixture[] {
  const dir = join(import.meta.dirname, 'fixtures', 'prover')
  const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort()
  return files.map((f) => {
    const raw = readFileSync(join(dir, f), 'utf-8')
    return JSON.parse(raw) as Fixture
  })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('BatchAVLProver — byte-for-byte against Rust', () => {
  const fixtures = loadFixtures()

  // Sanity: must have at least the bug-scenario fixture
  it('has fixtures loaded', () => {
    expect(fixtures.length).toBeGreaterThanOrEqual(1)
    const names = fixtures.map((f) => f.name)
    expect(names).toContain('insert-genproof-remove-genproof')
    expect(names).toContain('multi-batch-insert-insert-update')
  })

  for (const fix of fixtures) {
    it(fix.name, () => {
      const prover = new BatchAVLProver(
        fix.config.keyLength,
        fix.config.valueLengthOpt,
      )

      const operations = fix.operations.map(jsonToOp)
      let genIdx = 0

      for (let i = 0; i < operations.length; i++) {
        const result = prover.performOneOperation(operations[i]!)
        expect(result.success).toBe(true)

        if (
          genIdx < fix.genProofAfter.length &&
          fix.genProofAfter[genIdx] === i
        ) {
          const proof = prover.generateProof()
          const digest = prover.digest()!

          const actualProofHex = bytesToHex(proof)
          const actualDigestHex = bytesToHex(digest)

          expect(actualProofHex).toBe(fix.expectedProofs[genIdx])
          expect(actualDigestHex).toBe(fix.expectedDigests[genIdx])

          genIdx++
        }
      }

      // All genProofAfter indices must have been consumed
      expect(genIdx).toBe(fix.genProofAfter.length)
    })
  }
})
